blank_issues_enabled: false
contact_links:
    - name: ğŸ’ Support
      url: https://discord.riven.tv
      about: "This issue tracker is not for support questions. Join us on Discord for assistance!"
    - name: ğŸ“˜ Documentation
      url: https://riven.tv
      about: File an issue or make an improvement to the docs website.
    - name: ğŸ’¡ Ideas for New Features and Improvements
      url: https://github.com/rivenmedia/riven-frontend/discussions
      about: Propose and discuss future improvements to Riven
    - name: ğŸ‘¾ Chat
      url: https://discord.riven.tv
      about: Our Discord server is active, come join us!
